# Generated by Django 2.1.5 on 2019-01-13 17:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField(unique=True)),
                ('password', models.TextField(default='')),
                ('ip', models.TextField()),
                ('mac', models.TextField()),
                ('tariff_id', models.IntegerField()),
                ('network_id', models.IntegerField()),
                ('money', models.IntegerField()),
                ('state_id', models.IntegerField()),
                ('first_name', models.TextField()),
                ('second_name', models.TextField()),
                ('third_name', models.TextField()),
                ('description', models.TextField()),
                ('links', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('is_online', models.BooleanField()),
            ],
            options={
                'db_table': 'Abonents',
            },
        ),
    ]
