# Generated by Django 2.1.5 on 2019-01-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abonents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='abonents',
            table='abonents',
        ),
    ]
