# Generated by Django 2.1.5 on 2019-01-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonents', '0002_auto_20190113_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonents',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='abonents',
            name='first_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='abonents',
            name='ip',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='abonents',
            name='mac',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='abonents',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abonents',
            name='network_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='abonents',
            name='second_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='abonents',
            name='state_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='abonents',
            name='tariff_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='abonents',
            name='third_name',
            field=models.TextField(blank=True),
        ),
    ]
