# Generated by Django 2.1.5 on 2019-01-23 20:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonents', '0003_auto_20190113_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.TextField()),
                ('netmask', models.TextField()),
                ('ip', models.TextField()),
                ('description', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Speed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('local_in', models.IntegerField()),
                ('local_out', models.IntegerField()),
                ('world_in', models.IntegerField()),
                ('world_out', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('status', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tariffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('payment', models.IntegerField()),
                ('description', models.IntegerField(null=True)),
                ('speed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonents.Speed')),
            ],
        ),
        migrations.RemoveField(
            model_name='abonents',
            name='network_id',
        ),
        migrations.RemoveField(
            model_name='abonents',
            name='state_id',
        ),
        migrations.RemoveField(
            model_name='abonents',
            name='tariff_id',
        ),
        migrations.AlterField(
            model_name='abonents',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abonents',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='abonents',
            name='password',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='abonents',
            name='third_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abonents',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonents.Networks'),
        ),
        migrations.AddField(
            model_name='abonents',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonents.States'),
        ),
        migrations.AddField(
            model_name='abonents',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonents.Tariffs'),
        ),
    ]
